version: '3'
services:
  mongodb:
#    TODO Use proper pwd handling
    image: mongo:4.4.6
    ports:
      - 27017:27017
    restart: unless-stopped
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test1
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
  node_modules: